spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 80
